# ------------------------------
# Site
# ------------------------------
siteConfig:
  lang: zh-Hans
  domain: shyrz.me
  title: Shyrz
  description: Life, the Universe and Everything.
  avatar:
  url: https://shyrz.me
  license:
    text: CC BY-NC-ND 4.0
    link: https://creativecommons.org/licenses/by-nc-nd/4.0/
  pagination:
    prevPage: 返回
    nextPage: 更多文章
    prevPost: 上一篇
    nextPost: 下一篇


# ------------------------------
# Theme
# ------------------------------
# theme: tailsaw
# theme: minima
# theme: paper
theme: ./theme
themeConfig:
  nav:
    - text: 首页
      link: /
    - text: 关于
      link: /about.html
    - text: 友人
      link: /friends.html
  contact:
    keybase: shyrz
    dribbble: username
    facebook: username
    flickr: username
    github: shyrz
    instagram: username
    linkedin: username
    medium: shyrz
    pinterest: username
    twitter: dirus0
    youtube: username
    telegram: dirus0
    microblog: username
    googleplus: username
  disqus: shyrz


markdown:
  options:
    html: true
    xhtmlOut: true
    breaks: true
    linkify: true
    typographer: true
  headings:
    permalink: true
    # permalinkSymbol: ➦
  plugins:
    # - markdown-it-emoji
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-task-lists
    - markdown-it-deflist
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-container


# ------------------------------
# Plugins
# ------------------------------
plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
  # - saber-plugin-prismjs
  # - saber-plugin-search
